onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/bit_counter
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/bit_out
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/clk
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/counter
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/enable
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/lcr
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/lsr_mask
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/parity_xor
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_idle
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_pop_byte
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_send_byte
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_send_parity
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_send_start
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/s_send_stop
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/shift_out
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/stx_o_tmp
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/stx_pad_o
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_count
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_data_in
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_data_out
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_overrun
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_pop
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tf_push
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tstate
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/tx_reset
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/wb_dat_i
add wave -noupdate /uart16550_tb/uart0/regs/transmitter/wb_rst_i
add wave -noupdate /uart16550_tb/uart0/regs/receiver/clk
add wave -noupdate /uart16550_tb/uart0/regs/receiver/wb_rst_i
add wave -noupdate /uart16550_tb/uart0/regs/receiver/lcr
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_pop
add wave -noupdate /uart16550_tb/uart0/regs/receiver/srx_pad_i
add wave -noupdate /uart16550_tb/uart0/regs/receiver/enable
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rx_reset
add wave -noupdate /uart16550_tb/uart0/regs/receiver/lsr_mask
add wave -noupdate /uart16550_tb/uart0/regs/receiver/counter_t
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_count
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_data_out
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_overrun
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_error_bit
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rstate
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_push_pulse
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rcounter16
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rbit_counter
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rshift
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rparity
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rparity_error
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rframing_error
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rbit_in
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rparity_xor
add wave -noupdate /uart16550_tb/uart0/regs/receiver/counter_b
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_push_q
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_data_in
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rf_push
add wave -noupdate /uart16550_tb/uart0/regs/receiver/break_error
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rcounter16_eq_7
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rcounter16_eq_0
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rcounter16_eq_1
add wave -noupdate /uart16550_tb/uart0/regs/receiver/rcounter16_minus_1
add wave -noupdate /uart16550_tb/uart0/regs/receiver/toc_value
add wave -noupdate /uart16550_tb/uart0/regs/receiver/brc_value
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {970 ps} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
